matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: trusty
      sudo: required

    branches:
      only:
      - master

    before_script:
      - cd src/Hypnonema.NUI
      - npm install -g @angular/cli
    script:
      - ng lint
      - ng build --prod --base-href ./ --output-hashing none

    - language: csharp
      solution: Hypnonema.sln
      script:
        - xbuild /P:Configuration=Release Hypnonema.sln 
     
